name: Deploy to GithubPages

on: 
  branches:
    - master
permissions:
  contents: write
jobs:
  deploy-to-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          BRANCH: gh-pages
          FOLDER: base-concepts # The folder the action should deploy.